### ISSUE TITLE
should't this be 10002 not 10102?

### ISSUE THREAD

**Issue by gsovereignty** [pablof7z/wiki#26]
https://github.com/pablof7z/wiki/blob/1126db9a89c3e793f53dd2ebd6aa763ced655ef5/apps/web/src/lib/stores/session.ts#L146

**Comment by pablof7z** [comment]
no

https://github.com/nostr-protocol/nips/pull/787/files#diff-0d42225c4bd69ef69ef24d2de380ff90ca763019d04692558a1b78adeda25d50R36
